#include "glfwcxx/KeyboardHelper.hpp"

#include <GLFW/glfw3.h>

#include "glfwcxx/KeyboardInput.hpp"

#define GLFWCXX_TO_GLFW_CASE(glfwcxx_value, glfw_value) \
    case glfwcxx_value:                                 \
        return glfw_value;

#define GLFW_TO_GLFWCXX_CASE(glfwcxx_value, glfw_value) \
    case glfw_value:                                    \
        return glfwcxx_value;

#define GLFWCXX_ENUM_DEFAULT(glfwcxx_value) \
    default:                                \
        return glfwcxx_value;

#define GLFWCXX_DEFAULT() \
    default:              \
        return -1;

namespace glfwcxx::helpers {

auto glfw_keyboard_key(const input::KeyboardKey& key) -> int
{
    switch (key) {
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_unknown, GLFW_KEY_UNKNOWN)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_space, GLFW_KEY_SPACE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_apostrophe, GLFW_KEY_APOSTROPHE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_comma, GLFW_KEY_COMMA)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_minus, GLFW_KEY_MINUS)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_period, GLFW_KEY_PERIOD)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_slash, GLFW_KEY_SLASH)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_0, GLFW_KEY_0)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_1, GLFW_KEY_1)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_2, GLFW_KEY_2)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_3, GLFW_KEY_3)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_4, GLFW_KEY_4)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_5, GLFW_KEY_5)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_6, GLFW_KEY_6)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_7, GLFW_KEY_7)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_8, GLFW_KEY_8)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_9, GLFW_KEY_9)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_semicolon, GLFW_KEY_SEMICOLON)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_equal, GLFW_KEY_EQUAL)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_a, GLFW_KEY_A)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_b, GLFW_KEY_B)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_c, GLFW_KEY_C)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_d, GLFW_KEY_D)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_e, GLFW_KEY_E)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f, GLFW_KEY_F)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_g, GLFW_KEY_G)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_h, GLFW_KEY_H)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_i, GLFW_KEY_I)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_j, GLFW_KEY_J)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_k, GLFW_KEY_K)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_l, GLFW_KEY_L)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_m, GLFW_KEY_M)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_n, GLFW_KEY_N)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_o, GLFW_KEY_O)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_p, GLFW_KEY_P)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_q, GLFW_KEY_Q)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_r, GLFW_KEY_R)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_s, GLFW_KEY_S)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_t, GLFW_KEY_T)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_u, GLFW_KEY_U)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_v, GLFW_KEY_V)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_w, GLFW_KEY_W)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_x, GLFW_KEY_X)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_y, GLFW_KEY_Y)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_z, GLFW_KEY_Z)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_left_bracket, GLFW_KEY_LEFT_BRACKET)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_backslash, GLFW_KEY_BACKSLASH)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_right_bracket, GLFW_KEY_RIGHT_BRACKET)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_grave_accent, GLFW_KEY_GRAVE_ACCENT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_world_1, GLFW_KEY_WORLD_1)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_world_2, GLFW_KEY_WORLD_2)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_escape, GLFW_KEY_ESCAPE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_enter, GLFW_KEY_ENTER)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_tab, GLFW_KEY_TAB)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_backspace, GLFW_KEY_BACKSPACE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_insert, GLFW_KEY_INSERT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_delete, GLFW_KEY_DELETE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_right, GLFW_KEY_RIGHT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_left, GLFW_KEY_LEFT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_down, GLFW_KEY_DOWN)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_up, GLFW_KEY_UP)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_page_up, GLFW_KEY_PAGE_UP)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_page_down, GLFW_KEY_PAGE_DOWN)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_home, GLFW_KEY_HOME)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_end, GLFW_KEY_END)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_caps_lock, GLFW_KEY_CAPS_LOCK)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_scroll_lock, GLFW_KEY_SCROLL_LOCK)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_num_lock, GLFW_KEY_NUM_LOCK)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_print_screen, GLFW_KEY_PRINT_SCREEN)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_pause, GLFW_KEY_PAUSE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f1, GLFW_KEY_F1)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f2, GLFW_KEY_F2)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f3, GLFW_KEY_F3)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f4, GLFW_KEY_F4)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f5, GLFW_KEY_F5)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f6, GLFW_KEY_F6)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f7, GLFW_KEY_F7)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f8, GLFW_KEY_F8)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f9, GLFW_KEY_F9)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f10, GLFW_KEY_F10)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f11, GLFW_KEY_F11)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f12, GLFW_KEY_F12)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f13, GLFW_KEY_F13)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f14, GLFW_KEY_F14)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f15, GLFW_KEY_F15)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f16, GLFW_KEY_F16)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f17, GLFW_KEY_F17)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f18, GLFW_KEY_F18)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f19, GLFW_KEY_F19)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f20, GLFW_KEY_F20)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f21, GLFW_KEY_F21)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f22, GLFW_KEY_F22)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f23, GLFW_KEY_F23)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f24, GLFW_KEY_F24)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_f25, GLFW_KEY_F25)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_0, GLFW_KEY_KP_0)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_1, GLFW_KEY_KP_1)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_2, GLFW_KEY_KP_2)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_3, GLFW_KEY_KP_3)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_4, GLFW_KEY_KP_4)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_5, GLFW_KEY_KP_5)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_6, GLFW_KEY_KP_6)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_7, GLFW_KEY_KP_7)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_8, GLFW_KEY_KP_8)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_9, GLFW_KEY_KP_9)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_decimal, GLFW_KEY_KP_DECIMAL)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_divide, GLFW_KEY_KP_DIVIDE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_multiply, GLFW_KEY_KP_MULTIPLY)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_subtract, GLFW_KEY_KP_SUBTRACT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_add, GLFW_KEY_KP_ADD)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_enter, GLFW_KEY_KP_ENTER)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_kp_equal, GLFW_KEY_KP_EQUAL)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_left_shift, GLFW_KEY_LEFT_SHIFT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_left_control, GLFW_KEY_LEFT_CONTROL)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_left_alt, GLFW_KEY_LEFT_ALT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_left_super, GLFW_KEY_LEFT_SUPER)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_right_shift, GLFW_KEY_RIGHT_SHIFT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_right_control, GLFW_KEY_RIGHT_CONTROL)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_right_alt, GLFW_KEY_RIGHT_ALT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_right_super, GLFW_KEY_RIGHT_SUPER)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKey::key_menu, GLFW_KEY_MENU)
        GLFWCXX_DEFAULT()
    }
}

auto glfw_keyboard_action(const input::KeyboardAction& action) -> int
{
    switch (action) {
        GLFWCXX_TO_GLFW_CASE(input::KeyboardAction::release, GLFW_RELEASE)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardAction::press, GLFW_PRESS)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardAction::repeat, GLFW_REPEAT)
        GLFWCXX_DEFAULT()
    }
}

auto glfw_keyboard_modifier(const input::KeyboardKeyModifier& modifier) -> int
{
    switch (modifier) {
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKeyModifier::mod_shift, GLFW_MOD_SHIFT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKeyModifier::mod_control, GLFW_MOD_CONTROL)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKeyModifier::mod_alt, GLFW_MOD_ALT)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKeyModifier::mod_super, GLFW_MOD_SUPER)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKeyModifier::mod_caps_lock, GLFW_MOD_CAPS_LOCK)
        GLFWCXX_TO_GLFW_CASE(input::KeyboardKeyModifier::mod_num_lock, GLFW_MOD_NUM_LOCK)
        GLFWCXX_DEFAULT()
    }
}

auto glfwcxx_keyboard_key(int key) -> input::KeyboardKey
{
    switch (key) {
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_unknown, GLFW_KEY_UNKNOWN)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_space, GLFW_KEY_SPACE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_apostrophe, GLFW_KEY_APOSTROPHE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_comma, GLFW_KEY_COMMA)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_minus, GLFW_KEY_MINUS)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_period, GLFW_KEY_PERIOD)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_slash, GLFW_KEY_SLASH)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_0, GLFW_KEY_0)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_1, GLFW_KEY_1)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_2, GLFW_KEY_2)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_3, GLFW_KEY_3)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_4, GLFW_KEY_4)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_5, GLFW_KEY_5)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_6, GLFW_KEY_6)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_7, GLFW_KEY_7)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_8, GLFW_KEY_8)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_9, GLFW_KEY_9)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_semicolon, GLFW_KEY_SEMICOLON)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_equal, GLFW_KEY_EQUAL)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_a, GLFW_KEY_A)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_b, GLFW_KEY_B)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_c, GLFW_KEY_C)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_d, GLFW_KEY_D)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_e, GLFW_KEY_E)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f, GLFW_KEY_F)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_g, GLFW_KEY_G)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_h, GLFW_KEY_H)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_i, GLFW_KEY_I)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_j, GLFW_KEY_J)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_k, GLFW_KEY_K)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_l, GLFW_KEY_L)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_m, GLFW_KEY_M)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_n, GLFW_KEY_N)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_o, GLFW_KEY_O)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_p, GLFW_KEY_P)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_q, GLFW_KEY_Q)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_r, GLFW_KEY_R)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_s, GLFW_KEY_S)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_t, GLFW_KEY_T)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_u, GLFW_KEY_U)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_v, GLFW_KEY_V)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_w, GLFW_KEY_W)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_x, GLFW_KEY_X)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_y, GLFW_KEY_Y)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_z, GLFW_KEY_Z)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_left_bracket, GLFW_KEY_LEFT_BRACKET)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_backslash, GLFW_KEY_BACKSLASH)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_right_bracket, GLFW_KEY_RIGHT_BRACKET)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_grave_accent, GLFW_KEY_GRAVE_ACCENT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_world_1, GLFW_KEY_WORLD_1)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_world_2, GLFW_KEY_WORLD_2)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_escape, GLFW_KEY_ESCAPE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_enter, GLFW_KEY_ENTER)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_tab, GLFW_KEY_TAB)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_backspace, GLFW_KEY_BACKSPACE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_insert, GLFW_KEY_INSERT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_delete, GLFW_KEY_DELETE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_right, GLFW_KEY_RIGHT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_left, GLFW_KEY_LEFT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_down, GLFW_KEY_DOWN)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_up, GLFW_KEY_UP)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_page_up, GLFW_KEY_PAGE_UP)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_page_down, GLFW_KEY_PAGE_DOWN)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_home, GLFW_KEY_HOME)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_end, GLFW_KEY_END)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_caps_lock, GLFW_KEY_CAPS_LOCK)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_scroll_lock, GLFW_KEY_SCROLL_LOCK)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_num_lock, GLFW_KEY_NUM_LOCK)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_print_screen, GLFW_KEY_PRINT_SCREEN)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_pause, GLFW_KEY_PAUSE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f1, GLFW_KEY_F1)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f2, GLFW_KEY_F2)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f3, GLFW_KEY_F3)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f4, GLFW_KEY_F4)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f5, GLFW_KEY_F5)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f6, GLFW_KEY_F6)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f7, GLFW_KEY_F7)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f8, GLFW_KEY_F8)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f9, GLFW_KEY_F9)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f10, GLFW_KEY_F10)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f11, GLFW_KEY_F11)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f12, GLFW_KEY_F12)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f13, GLFW_KEY_F13)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f14, GLFW_KEY_F14)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f15, GLFW_KEY_F15)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f16, GLFW_KEY_F16)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f17, GLFW_KEY_F17)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f18, GLFW_KEY_F18)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f19, GLFW_KEY_F19)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f20, GLFW_KEY_F20)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f21, GLFW_KEY_F21)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f22, GLFW_KEY_F22)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f23, GLFW_KEY_F23)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f24, GLFW_KEY_F24)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_f25, GLFW_KEY_F25)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_0, GLFW_KEY_KP_0)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_1, GLFW_KEY_KP_1)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_2, GLFW_KEY_KP_2)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_3, GLFW_KEY_KP_3)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_4, GLFW_KEY_KP_4)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_5, GLFW_KEY_KP_5)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_6, GLFW_KEY_KP_6)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_7, GLFW_KEY_KP_7)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_8, GLFW_KEY_KP_8)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_9, GLFW_KEY_KP_9)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_decimal, GLFW_KEY_KP_DECIMAL)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_divide, GLFW_KEY_KP_DIVIDE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_multiply, GLFW_KEY_KP_MULTIPLY)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_subtract, GLFW_KEY_KP_SUBTRACT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_add, GLFW_KEY_KP_ADD)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_enter, GLFW_KEY_KP_ENTER)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_kp_equal, GLFW_KEY_KP_EQUAL)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_left_shift, GLFW_KEY_LEFT_SHIFT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_left_control, GLFW_KEY_LEFT_CONTROL)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_left_alt, GLFW_KEY_LEFT_ALT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_left_super, GLFW_KEY_LEFT_SUPER)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_right_shift, GLFW_KEY_RIGHT_SHIFT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_right_control, GLFW_KEY_RIGHT_CONTROL)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_right_alt, GLFW_KEY_RIGHT_ALT)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_right_super, GLFW_KEY_RIGHT_SUPER)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardKey::key_menu, GLFW_KEY_MENU)
        GLFWCXX_ENUM_DEFAULT(input::KeyboardKey::invalid_key)
    }
}

auto glfwcxx_keyboard_action(int action) -> input::KeyboardAction
{
    switch (action) {
        GLFW_TO_GLFWCXX_CASE(input::KeyboardAction::release, GLFW_RELEASE)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardAction::press, GLFW_PRESS)
        GLFW_TO_GLFWCXX_CASE(input::KeyboardAction::repeat, GLFW_REPEAT)
        GLFWCXX_ENUM_DEFAULT(input::KeyboardAction::unknown)
    }
}

}  // namespace glfwcxx::helpers
