#pragma once

static constexpr int GLFW_FALSE = 0;
static constexpr int GLFW_TRUE = 1;

static constexpr int GLFW_JOYSTICK_HAT_BUTTONS = 0x00050001;
static constexpr int GLFW_COCOA_CHDIR_RESOURCES = 0x00051001;
static constexpr int GLFW_COCOA_MENUBAR = 0x00051002;

static constexpr int GLFW_DONT_CARE = -1;

static constexpr int GLFW_NO_ERROR = 0;
static constexpr int GLFW_NOT_INITIALIZED = 0x00010001;

static constexpr int GLFW_FOCUSED = 0x00020001;
static constexpr int GLFW_RESIZABLE = 0x00020003;
static constexpr int GLFW_VISIBLE = 0x00020004;
static constexpr int GLFW_DECORATED = 0x00020005;
static constexpr int GLFW_AUTO_ICONIFY = 0x00020006;
static constexpr int GLFW_FLOATING = 0x00020007;
static constexpr int GLFW_MAXIMIZED = 0x00020008;
static constexpr int GLFW_CENTER_CURSOR = 0x00020009;
static constexpr int GLFW_TRANSPARENT_FRAMEBUFFER = 0x0002000A;
static constexpr int GLFW_FOCUS_ON_SHOW = 0x0002000C;
static constexpr int GLFW_RED_BITS = 0x00021001;
static constexpr int GLFW_GREEN_BITS = 0x00021002;
static constexpr int GLFW_BLUE_BITS = 0x00021003;
static constexpr int GLFW_ALPHA_BITS = 0x00021004;
static constexpr int GLFW_DEPTH_BITS = 0x00021005;
static constexpr int GLFW_STENCIL_BITS = 0x00021006;
static constexpr int GLFW_ACCUM_RED_BITS = 0x00021007;
static constexpr int GLFW_ACCUM_GREEN_BITS = 0x00021008;
static constexpr int GLFW_ACCUM_BLUE_BITS = 0x00021009;
static constexpr int GLFW_ACCUM_ALPHA_BITS = 0x0002100A;
static constexpr int GLFW_AUX_BUFFERS = 0x0002100B;
static constexpr int GLFW_STEREO = 0x0002100C;
static constexpr int GLFW_SAMPLES = 0x0002100D;
static constexpr int GLFW_SRGB_CAPABLE = 0x0002100D;
static constexpr int GLFW_REFRESH_RATE = 0x0002100F;
static constexpr int GLFW_DOUBLEBUFFER = 0x00021010;
static constexpr int GLFW_CLIENT_API = 0x00022001;
static constexpr int GLFW_CONTEXT_VERSION_MAJOR = 0x00022002;
static constexpr int GLFW_CONTEXT_VERSION_MINOR = 0x00022003;
static constexpr int GLFW_CONTEXT_ROBUSTNESS = 0x00022003;
static constexpr int GLFW_OPENGL_FORWARD_COMPAT = 0x00022006;
static constexpr int GLFW_OPENGL_DEBUG_CONTEXT = 0x00022007;
static constexpr int GLFW_OPENGL_PROFILE = 0x00022008;
static constexpr int GLFW_CONTEXT_RELEASE_BEHAVIOR = 0x00022008;
static constexpr int GLFW_CONTEXT_CREATION_API = 0x0002200B;
static constexpr int GLFW_SCALE_TO_MONITOR = 0x0002200C;
static constexpr int GLFW_COCOA_RETINA_FRAMEBUFFER = 0x00023001;
static constexpr int GLFW_COCOA_FRAME_NAME = 0x00023002;
static constexpr int GLFW_COCOA_GRAPHICS_SWITCHING = 0x00023003;
static constexpr int GLFW_X11_CLASS_NAME = 0x00024001;
static constexpr int GLFW_X11_INSTANCE_NAME = 0x00024002;

static constexpr int GLFW_NO_API = 0;
static constexpr int GLFW_OPENGL_API = 0x00030001;
static constexpr int GLFW_OPENGL_ES_API = 0x00030002;

static constexpr int GLFW_NO_ROBUSTNESS = 0;
static constexpr int GLFW_NO_RESET_NOTIFICATION = 0x00031001;
static constexpr int GLFW_LOSE_CONTEXT_ON_RESET = 0x00031002;

static constexpr int GLFW_OPENGL_ANY_PROFILE = 0;
static constexpr int GLFW_OPENGL_CORE_PROFILE = 0x00032001;
static constexpr int GLFW_OPENGL_COMPAT_PROFILE = 0x00032002;

static constexpr int GLFW_ANY_RELEASE_BEHAVIOR = 0;
static constexpr int GLFW_RELEASE_BEHAVIOR_FLUSH = 0x00035001;
static constexpr int GLFW_RELEASE_BEHAVIOR_NONE = 0x00035002;

static constexpr int GLFW_NATIVE_CONTEXT_API = 0x00036001;
static constexpr int GLFW_EGL_CONTEXT_API = 0x00036002;
static constexpr int GLFW_OSMESA_CONTEXT_API = 0x00036003;

static constexpr int GLFW_RELEASE = 0;
static constexpr int GLFW_PRESS = 1;
static constexpr int GLFW_REPEAT = 2;

static constexpr int GLFW_KEY_UNKNOWN = -1;
static constexpr int GLFW_KEY_SPACE = 32;
static constexpr int GLFW_KEY_APOSTROPHE = 39;
static constexpr int GLFW_KEY_COMMA = 44;
static constexpr int GLFW_KEY_MINUS = 45;
static constexpr int GLFW_KEY_PERIOD = 46;
static constexpr int GLFW_KEY_SLASH = 47;
static constexpr int GLFW_KEY_0 = 48;
static constexpr int GLFW_KEY_1 = 49;
static constexpr int GLFW_KEY_2 = 50;
static constexpr int GLFW_KEY_3 = 51;
static constexpr int GLFW_KEY_4 = 52;
static constexpr int GLFW_KEY_5 = 53;
static constexpr int GLFW_KEY_6 = 54;
static constexpr int GLFW_KEY_7 = 55;
static constexpr int GLFW_KEY_8 = 56;
static constexpr int GLFW_KEY_9 = 57;
static constexpr int GLFW_KEY_SEMICOLON = 59;
static constexpr int GLFW_KEY_EQUAL = 61;
static constexpr int GLFW_KEY_A = 65;
static constexpr int GLFW_KEY_B = 66;
static constexpr int GLFW_KEY_C = 67;
static constexpr int GLFW_KEY_D = 68;
static constexpr int GLFW_KEY_E = 69;
static constexpr int GLFW_KEY_F = 70;
static constexpr int GLFW_KEY_G = 71;
static constexpr int GLFW_KEY_H = 72;
static constexpr int GLFW_KEY_I = 73;
static constexpr int GLFW_KEY_J = 74;
static constexpr int GLFW_KEY_K = 75;
static constexpr int GLFW_KEY_L = 76;
static constexpr int GLFW_KEY_M = 77;
static constexpr int GLFW_KEY_N = 78;
static constexpr int GLFW_KEY_O = 79;
static constexpr int GLFW_KEY_P = 80;
static constexpr int GLFW_KEY_Q = 81;
static constexpr int GLFW_KEY_R = 82;
static constexpr int GLFW_KEY_S = 83;
static constexpr int GLFW_KEY_T = 84;
static constexpr int GLFW_KEY_U = 85;
static constexpr int GLFW_KEY_V = 86;
static constexpr int GLFW_KEY_W = 87;
static constexpr int GLFW_KEY_X = 88;
static constexpr int GLFW_KEY_Y = 89;
static constexpr int GLFW_KEY_Z = 90;
static constexpr int GLFW_KEY_LEFT_BRACKET = 91;
static constexpr int GLFW_KEY_BACKSLASH = 92;
static constexpr int GLFW_KEY_RIGHT_BRACKET = 93;
static constexpr int GLFW_KEY_GRAVE_ACCENT = 96;
static constexpr int GLFW_KEY_WORLD_1 = 161;
static constexpr int GLFW_KEY_WORLD_2 = 162;
static constexpr int GLFW_KEY_ESCAPE = 256;
static constexpr int GLFW_KEY_ENTER = 257;
static constexpr int GLFW_KEY_TAB = 258;
static constexpr int GLFW_KEY_BACKSPACE = 259;
static constexpr int GLFW_KEY_INSERT = 260;
static constexpr int GLFW_KEY_DELETE = 261;
static constexpr int GLFW_KEY_RIGHT = 262;
static constexpr int GLFW_KEY_LEFT = 263;
static constexpr int GLFW_KEY_DOWN = 264;
static constexpr int GLFW_KEY_UP = 265;
static constexpr int GLFW_KEY_PAGE_UP = 266;
static constexpr int GLFW_KEY_PAGE_DOWN = 267;
static constexpr int GLFW_KEY_HOME = 268;
static constexpr int GLFW_KEY_END = 269;
static constexpr int GLFW_KEY_CAPS_LOCK = 280;
static constexpr int GLFW_KEY_SCROLL_LOCK = 281;
static constexpr int GLFW_KEY_NUM_LOCK = 282;
static constexpr int GLFW_KEY_PRINT_SCREEN = 283;
static constexpr int GLFW_KEY_PAUSE = 284;
static constexpr int GLFW_KEY_F1 = 290;
static constexpr int GLFW_KEY_F2 = 291;
static constexpr int GLFW_KEY_F3 = 292;
static constexpr int GLFW_KEY_F4 = 293;
static constexpr int GLFW_KEY_F5 = 294;
static constexpr int GLFW_KEY_F6 = 295;
static constexpr int GLFW_KEY_F7 = 296;
static constexpr int GLFW_KEY_F8 = 297;
static constexpr int GLFW_KEY_F9 = 298;
static constexpr int GLFW_KEY_F10 = 299;
static constexpr int GLFW_KEY_F11 = 300;
static constexpr int GLFW_KEY_F12 = 301;
static constexpr int GLFW_KEY_F13 = 302;
static constexpr int GLFW_KEY_F14 = 303;
static constexpr int GLFW_KEY_F15 = 304;
static constexpr int GLFW_KEY_F16 = 305;
static constexpr int GLFW_KEY_F17 = 306;
static constexpr int GLFW_KEY_F18 = 307;
static constexpr int GLFW_KEY_F19 = 308;
static constexpr int GLFW_KEY_F20 = 309;
static constexpr int GLFW_KEY_F21 = 310;
static constexpr int GLFW_KEY_F22 = 311;
static constexpr int GLFW_KEY_F23 = 312;
static constexpr int GLFW_KEY_F24 = 313;
static constexpr int GLFW_KEY_F25 = 314;
static constexpr int GLFW_KEY_KP_0 = 320;
static constexpr int GLFW_KEY_KP_1 = 321;
static constexpr int GLFW_KEY_KP_2 = 322;
static constexpr int GLFW_KEY_KP_3 = 323;
static constexpr int GLFW_KEY_KP_4 = 324;
static constexpr int GLFW_KEY_KP_5 = 325;
static constexpr int GLFW_KEY_KP_6 = 326;
static constexpr int GLFW_KEY_KP_7 = 327;
static constexpr int GLFW_KEY_KP_8 = 328;
static constexpr int GLFW_KEY_KP_9 = 329;
static constexpr int GLFW_KEY_KP_DECIMAL = 330;
static constexpr int GLFW_KEY_KP_DIVIDE = 331;
static constexpr int GLFW_KEY_KP_MULTIPLY = 332;
static constexpr int GLFW_KEY_KP_SUBTRACT = 333;
static constexpr int GLFW_KEY_KP_ADD = 334;
static constexpr int GLFW_KEY_KP_ENTER = 335;
static constexpr int GLFW_KEY_KP_EQUAL = 336;
static constexpr int GLFW_KEY_LEFT_SHIFT = 340;
static constexpr int GLFW_KEY_LEFT_CONTROL = 341;
static constexpr int GLFW_KEY_LEFT_ALT = 342;
static constexpr int GLFW_KEY_LEFT_SUPER = 343;
static constexpr int GLFW_KEY_RIGHT_SHIFT = 344;
static constexpr int GLFW_KEY_RIGHT_CONTROL = 345;
static constexpr int GLFW_KEY_RIGHT_ALT = 346;
static constexpr int GLFW_KEY_RIGHT_SUPER = 347;
static constexpr int GLFW_KEY_MENU = 348;

static constexpr int GLFW_MOD_SHIFT = 0x0001;
static constexpr int GLFW_MOD_CONTROL = 0x0002;
static constexpr int GLFW_MOD_ALT = 0x0004;
static constexpr int GLFW_MOD_SUPER = 0x0008;
static constexpr int GLFW_MOD_CAPS_LOCK = 0x0010;
static constexpr int GLFW_MOD_NUM_LOCK = 0x0020;

struct GLFWmonitor;
struct GLFWwindow;

using GLFWkeyfun = void (*)(GLFWwindow* window, int key, int scancode, int action, int mods);

extern auto glfwGetError(const char** description) -> int;

extern auto glfwInit() -> int;
extern auto glfwTerminate() -> void;
extern auto glfwInitHint(int hint, int value) -> void;

extern auto glfwCreateWindow(int width, int height, const char* title, GLFWmonitor* monitor, GLFWwindow* share) -> GLFWwindow*;
extern auto glfwDestroyWindow(GLFWwindow* window) -> void;
extern auto glfwMakeContextCurrent(GLFWwindow* window) -> void;
extern auto glfwWindowHint(int hint, int value) -> void;
extern auto glfwWindowHintString(int hint, const char* value) -> void;
extern auto glfwPollEvents() -> void;
extern auto glfwSwapBuffers(GLFWwindow* window) -> void;
extern auto glfwWindowShouldClose(GLFWwindow* window) -> int;
extern auto glfwSetWindowShouldClose(GLFWwindow* window, int value) -> void;
extern auto glfwSetKeyCallback(GLFWwindow* window, GLFWkeyfun callback) -> GLFWkeyfun;
extern auto glfwSetWindowUserPointer(GLFWwindow* window, void* pointer) -> void;
extern auto glfwGetWindowUserPointer(GLFWwindow* window) -> void*;
